id: P003085
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:39:26.348246
source_metadata:
  id: bdr:W1KG22001
  title: འཛམ་གླིང་གི་ཆོས་ལུགས་ཁག་བཅུའི་ངོ་སྤྲོད་བློ་གསལ་བུང་བའི་དགའ་སྟོན།
  author: ''
  volumes:
    18564ed9926e4f83b851741da9a248ad:
      image_group_id: I1KG22080
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
