id: P003085
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22001
  title: འཛམ་གླིང་གི་ཆོས་ལུགས་ཁག་བཅུའི་ངོ་སྤྲོད་བློ་གསལ་བུང་བའི་དགའ་སྟོན།
  author: ''
  volumes:
    18564ed9926e4f83b851741da9a248ad:
      image_group_id: I1KG22080
      title: ''
      volume_number: 1
      total_pages: 178
